Разметка главной страницы
htmlacademy-adaptive/841461-cat-energy-23 pull request #2
Opened 2021-07-28 12:45 UTC by Gerda0283

Отправляю главную

2021-07-28 17:54 UTC, andreysgra requested changes

2021-07-28 17:54 UTC, andreysgra commented on source/index.html
> +                  <li class="menu__item">
Ошибки БЭМ. Давайте разберём на этом примере, почему.

Класс `menu__item` согласно БЭМ указывает на то, что это БЭМ элемент. Элемент это всегда производное от БЭМ блока. `menu__item` элемент блока `menu`, но блока с таким классом среди родителей `menu__item` нет, вот и появляется ошибка.

Как нужно поступить: родительским элементом `menu__item` является `main-nav__list`, но это класс БЭМ элемента и делать производные от элемента нельзя. То есть такая запись `main-nav__list__item` будет некорректной, так как название класса будет расшифровываться как элемент элемента. К счастью, этому элементу вы добавили и класс БЭМ блока `menu-list`, а значит для `li` можно использовать префикс `menu-list__`. Правильное название класса будет `menu-list__item`.

Не забывайте проверять синтаксис БЭМ в этом [сервисе](https://yoksel.github.io/html-tree/) (ссылку на него давал ранее, в переписке, но на всякий случай повторю здесь).

2021-07-28 17:54 UTC, andreysgra commented on source/index.html
> +              <div class="product-define__icon icon_weight-loss"></div><!--Реализация через фигуру + псевдокласс или спрайт-->
Ошибки БЭМ.

2021-07-28 17:54 UTC, andreysgra commented on source/index.html
> +              <div class="product-define__icon icon_weight-gain "></div><!--Реализация через фигуру + псевдокласс или спрайт-->
Ошибки БЭМ.

2021-07-28 17:54 UTC, andreysgra commented on source/index.html
> +              <div class="feature__icon feature_description-item"></div><!--Реализация псевдоклассом и фигурой-->
Ошибки БЭМ.

2021-07-28 17:54 UTC, andreysgra commented on source/index.html
> +            <ul class="social__list social">
Ошибки БЭМ.

2021-07-28 17:54 UTC, andreysgra commented on source/index.html
> +                <a class="social-link social__link_vkontakte" href="https://vk.com/htmlacademy">
Ошибки БЭМ.

2021-07-28 17:54 UTC, andreysgra commented on source/index.html
> +                <a class="social-link social__link_facebook" href="https://www.facebook.com/htmlacademy">
Ошибки БЭМ.

2021-07-28 17:54 UTC, andreysgra commented on source/index.html
> +            <img class="copiright__logo developer-logo" src="img/htmlacademy.svg" width="27" height="34" alt="Логотип HTML Академии" /><!--Реализация через svg спрайт-->
Ошибки БЭМ.

2021-07-28 17:54 UTC, andreysgra commented on source/index.html
> +          </div>
Моё мнение: я бы эти два изображения макета
![image](https://user-images.githubusercontent.com/17790771/127367816-632dbc72-8f70-4fa9-a3c8-4ebebcf48a75.png)
объединил бы и экспортировал, как одно изображение.

В противном случае приходится делать две ссылки на главную страницу. На мой взгляд это несколько странно, учитывая, что в макете ещё есть и пункт меню, который ведёт туда же.

Ну и в десктопной версии мы видим, что тут уже одно изображение в макете и получится, что в этой версии одну из ссылок придётся скрывать.

2021-07-28 17:54 UTC, andreysgra commented on source/index.html
> +          <div class="cell cell_logo-img">
По названиям классов по БЭМ: `row`, `cell` с точки зрения БЭМ являются блоками и мы должны вынести в эти классы общие свойства. Мне пока трудно представить, какие общие свойства могут быть в данных классах, учитывая то, что они интенсивно используются в проекте. Такие классы подошли бы для какого-нибудь фреймворка CSS, но в нашей вёрстке скорее всего они будут мешать, а не приносить пользу.

Почему я считаю, что тут будет больше вреда, чем пользы: возьмём класс `cell`. Вы применили его к первому логотипу и тут же его модифицируете классом модификатора `cell_logo-img`. У следующего логотипа класс блока `cell` и модификатор `cell_text-format-logo`. Смотрим дальше - навигация `cell cell_navigate`. Снова модификатор. И так далее. Получается, что универсальности от класса `cell` минимум и в каждом новом блоке вам приходится модифицировать его свойства. Это очень усложнит в дальнейшем разработку и приведёт к путанице.

2021-07-28 17:54 UTC, andreysgra commented on source/index.html
> +          </div>
Скрытым заголовкам, которые нужны только скринридерам и поисковикам вряд ли нужна обёртка. Так что класс `visually-hidden` стоит применить непосредственно к `h2`, а `div` удалить.

2021-07-28 17:54 UTC, andreysgra commented on source/index.html
> +            <li class="product-define__item cell cell_product-define-theme">
Тут тоже переизбыток классов. `ul` стоит оставить только `product-type__list` и `product-type__list`, а `li` - `product-define__item`.

Дальше я уже не буду указывать на избыточность классов, а советую вам просто пересмотреть наименование классов и упростить по возможности. И кроме того, на этапе разметки нет необходимости продумывать всевозможные варианты, достаточно ограничиться базовым, наиболее очевидным набором классов и тегов, а дополнительные теги и классы добавлять по мере необходимости уже работая над стилизацией сайта.

2021-07-28 17:54 UTC, andreysgra commented on source/index.html
> +              <hr class="divider product-define__hr">
Ну вот такие вещи по своей сути являются декоративными элементами. Реализуются средствами CSS и не стоит засорять разметку лишними тегами.
![image](https://user-images.githubusercontent.com/17790771/127370970-f0374b8b-d20d-4d31-9c31-e29400f736bb.png)

2021-07-28 17:54 UTC, andreysgra commented on source/index.html
> +              <div class="icon-number icon-number_one"></div><!--цифра через svg-->
Ну так если будет реализация через псевдо класс, то зачем в разметки аж целых два лишних `div`? 😼

2021-07-28 17:54 UTC, andreysgra commented on source/index.html
> +                </form>
Ой, а вот здесь форма совсем ни к чему. Форма нужна для отправки данных на сервер, а нам никакие данные отправлять из слайда ну нужно.

Также не советую этот элемент интерфейса
![image](https://user-images.githubusercontent.com/17790771/127371484-4f3a712d-02b4-4d9b-bd30-ba0bd243a380.png)
размечать тегом `<input type="range">`. Кроссбраузерная стилизация этого HTML элемента не тривиальна. Советую просто собрать его из `div`'ов и `button` (`button` размечается круг, который мы видим начиная с планшетной версии.

А вот это нужно разметить кнопками с типом `button`
![image](https://user-images.githubusercontent.com/17790771/127371999-34581a52-7dc0-4927-bdc8-227488afa0b8.png)

2021-07-28 20:21 UTC, Gerda0283 commented on source/index.html
> +                  <li class="menu__item">
Спасибо! Я там в некоторых местах такое исправляла. Видимо не везде. Сейчас проверю!

2021-07-28 20:26 UTC, Gerda0283 commented on source/index.html
> +          </div>
Согласна. На счёт главной - моё мнение -вообще недоработка. Такой пункт меню не логичен если есть ссылка с лого (или конечно можно лого делать не ссылкой, что тоже не юи - люди будут тыкать на логотип автоматически), а главную уж можно во внутренних страницах поставить, коль крох нету.

2021-07-28 20:30 UTC, Gerda0283 commented on source/index.html
> +          <div class="cell cell_logo-img">
Хотела сделать универсальную сетку и подганять под нужды некоторые ячейки модификаторами. Не используемые модификаторы думала удалить в процессе стилизации.
Но мысль была, что классов и так везде много, кно с базовых ячеек хотела сверстать каркас, а остальными блоками модифицировать.
Удаляем всё или только модификаторы?

2021-07-28 20:34 UTC, Gerda0283 commented on source/index.html
> +              <div class="icon-number icon-number_one"></div><!--цифра через svg-->
<div class="icon-number icon-number_one"></div><!--цифра через svg--> - этот див временный. Я его заменю на свг или свг со спрайта. Написала, чтобы видеть место. ьМогу правда просто коментами.

2021-07-28 20:35 UTC, Gerda0283 commented on source/index.html
> +                </form>
Оки, приступила к правкам

2021-07-28 22:12 UTC, Gerda0283 commented on source/index.html
> +          <div class="cell cell_logo-img">
Удалила все row. Пока оставила cell (Задумываются для  устройства сетки на гридах). Но посмотрим, может и их тоже того за нинадобностью

2021-07-28 22:13 UTC, Gerda0283 commented on source/index.html
> +            <li class="product-define__item cell cell_product-define-theme">
Вроде почистила

2021-07-29 17:30 UTC, andreysgra commented on source/index.html
> +          </div>
>Такой пункт меню не логичен если есть ссылка с лого (или конечно можно лого делать не ссылкой, что тоже не юи - люди будут тыкать на логотип автоматически), а главную уж можно во внутренних страницах поставить, коль крох нету.

Полностью согласен 😄.

2021-07-29 17:32 UTC, andreysgra commented on source/index.html
> +              <div class="icon-number icon-number_one"></div><!--цифра через svg-->
Хорошо.

2021-07-29 17:55 UTC, merged