Разметка внутренних страниц
htmlacademy-adaptive/841461-cat-energy-23 pull request #3
Opened 2021-07-29 23:13 UTC by Gerda0283

2021-07-30 12:56 UTC, andreysgra requested changes
Ну а в целом задание выполнено хорошо.

2021-07-30 12:56 UTC, andreysgra commented on source/catalog.html
> +                <button class="card__button button">заказать</button>
Ну это однозначно ссылка. Кнопка без JS мертва, поэтому делаем ссылкой с оглядкой на критическую функциональность сайта.

2021-07-30 12:56 UTC, andreysgra commented on source/catalog.html
> +            </li>
Типичная ошибка в большинстве реализаций данного проекта. Не стоит этот элемент интерфейса включать в список товаров `catalog-list`. Список - это объединение схожих по смыслу сущностей. Данный блок не описывает карточку товара, у него другое предназначение. Нужно вынести за пределы списка.

2021-07-30 12:56 UTC, andreysgra commented on source/catalog.html
> +                <button class="product__button button button_more-product">Показать все</button>
Тоже ссылки (с оглядкой на критическую функциональность сайта).

2021-07-30 12:56 UTC, andreysgra commented on source/catalog.html
> +                    <td class="btn-container"><button class="btn-container__button button">заказать</button></td>
![image](https://user-images.githubusercontent.com/17790771/127655298-9cec628b-3623-4091-b954-d92667466d23.png)

2021-07-30 12:56 UTC, andreysgra commented on source/form.html
> +      <form class="program-form">
Желательно указать `action` и `method`.

2021-07-30 12:56 UTC, andreysgra commented on source/form.html
> +                <input class="contact-info__input" type="text" name="phone-number" id="phone-number" placeholder="8 (960) 900-60-90"  required />
https://up.htmlacademy.ru/adaptive/23/project/cat-energy#cat-energy-5-2

2021-07-30 12:56 UTC, andreysgra commented on source/form.html
> +            <h2 class="section-headline">Контактные данные<br /> (владельца кота)</h2>
Нет смысла в легенду заворачивать заголовок. Легенда это и так заголовок группы полей.

В других местах тоже исправьте.

2021-07-30 15:17 UTC, Gerda0283 commented on source/form.html
> +                <input class="contact-info__input" type="text" name="phone-number" id="phone-number" placeholder="8 (960) 900-60-90"  required />
Про типы, поняла

2021-07-30 15:17 UTC, Gerda0283 commented on source/form.html
> +            <h2 class="section-headline">Контактные данные<br /> (владельца кота)</h2>
Хорошо

2021-07-30 15:37 UTC, Gerda0283 commented on source/catalog.html
> +                <button class="product__button button button_more-product">Показать все</button>
done!

2021-07-30 15:39 UTC, Gerda0283 commented on source/catalog.html
> +                    <td class="btn-container"><button class="btn-container__button button">заказать</button></td>
done!

2021-07-30 15:50 UTC, Gerda0283 commented on source/form.html
> +      <form class="program-form">
Done!

2021-07-30 15:52 UTC, Gerda0283 commented on source/form.html
> +                <input class="contact-info__input" type="text" name="phone-number" id="phone-number" placeholder="8 (960) 900-60-90"  required />
done!

2021-07-30 17:05 UTC, Gerda0283 commented on source/catalog.html
> +            </li>
Но кнопки, то кнопками здесь оставим? Тут им ссылки на мой взгляд никак не пришить

2021-07-31 17:55 UTC, andreysgra commented on source/catalog.html
> +            </li>
Как раз таки ссылки. Самые, что ни на есть.

2021-07-31 18:06 UTC, merged