Стилизация всех страниц
htmlacademy-adaptive/841461-cat-energy-23 pull request #4
Opened 2021-08-16 22:24 UTC by Gerda0283

Пожалуйста смотрите на ширине вьпорта 320 px.

2021-08-17 18:03 UTC, andreysgra requested changes
Что касается положения меню, при реализации без JS: в критерии Б31 первый пункт гласит: _Меню должно быть открыто по умолчанию и находиться в потоке **(то есть не перекрывать остальной контент)**_. Что мы видим сейчас, если отключим JS:
![image](https://user-images.githubusercontent.com/17790771/129777059-18ae8997-b858-4111-a053-797ca0cdfe96.png)
контент перекрыт.

В макете показано положение меню с включённым JS. Без JS меню должно выглядеть так:
![image](https://user-images.githubusercontent.com/17790771/129777358-65563686-79eb-45ae-aaa5-dbf85fe9bb2b.png)
находиться в потоке и сдвигать контент вниз.

2021-08-18 11:03 UTC, Gerda0283 commented on source/index.html
> +          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1998.6033013998237!2d30.32136833545218!3d59.938724543317974!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4696310fca
Видела там ошибку, но не разобралась бістро и решила оставить на потом

2021-08-18 11:04 UTC, Gerda0283 commented on source/catalog.html
> +          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1998.6033013998237!2d30.32136833545218!3d59.938724543317974!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4696310fca
Сделаю точніми значениями

2021-08-18 11:06 UTC, Gerda0283 commented on source/sass/add-component.scss
> +  .button_btn-container-theme {
Поняла, исправлю

2021-08-18 11:11 UTC, Gerda0283 commented on source/sass/global.scss
> +}
Поняла, думала заголовки как типографику можно внести. Но исправлю (ведь заготовила им классы ;-) )

2021-08-18 11:17 UTC, Gerda0283 commented on source/sass/style.scss
> +@import "../sass/normalize.scss";
Поняла, исправлю

2021-08-18 13:25 UTC, Gerda0283 commented on source/sass/add-component.scss
> +  gap: 0;
done!

2021-08-18 13:29 UTC, Gerda0283 commented on source/sass/add-component.scss
> +  .button_btn-container-theme {
done!

2021-08-18 13:35 UTC, Gerda0283 commented on source/sass/address-card.scss
> +}
done!

2021-08-18 14:47 UTC, Gerda0283 commented on source/sass/base-info-list.scss
> +.base-info__input {
done!

2021-08-18 15:27 UTC, Gerda0283 commented on source/sass/card.scss
> +.card-link {
done!

2021-08-18 15:38 UTC, Gerda0283 commented on source/sass/cat-weight-results.scss
> +.weight-time-list__item {
done!

2021-08-18 15:38 UTC, Gerda0283 commented on source/sass/cat-weight-results.scss
> +.weight-time-list__item_costs-theme {
done!

2021-08-18 15:59 UTC, Gerda0283 commented on source/sass/cat-weight.scss
> +.cat-weight .section-headline {
done!

2021-08-18 15:59 UTC, Gerda0283 commented on source/sass/features.scss
> +.features .section-headline {
done!

2021-08-18 15:59 UTC, Gerda0283 commented on source/sass/global.scss
> +}
done!

2021-08-18 16:00 UTC, Gerda0283 commented on source/sass/global.scss
> +  }
done!

2021-08-18 16:06 UTC, Gerda0283 commented on source/sass/global.scss
> +}
done!

2021-08-18 16:14 UTC, Gerda0283 commented on source/sass/main-nav.scss
> +  .main-nav_nojs .menu-list__item_current a {
done!

2021-08-18 16:14 UTC, Gerda0283 commented on source/sass/main-nav.scss
> +  .menu-list__item:last-child {
done!

2021-08-18 16:15 UTC, Gerda0283 commented on source/sass/main-nav.scss
> +}
done!

2021-08-18 16:26 UTC, Gerda0283 commented on source/sass/more-cards.scss
> +    .division-headline {
done!

2021-08-18 16:27 UTC, Gerda0283 commented on source/sass/more-cards.scss
> +.button_more-product {
done!

2021-08-18 16:59 UTC, Gerda0283 commented on source/sass/page-body.scss
> +.page-body_inner .logo-img {
done!

2021-08-18 17:02 UTC, Gerda0283 commented on source/sass/product-type-list.scss
> +.division-headline_product-type {
done!

2021-08-18 17:08 UTC, Gerda0283 commented on source/sass/program-main.scss
> +  .container_program-main {
done!

2021-08-18 17:09 UTC, Gerda0283 commented on source/sass/style.scss
> +@import "../sass/normalize.scss";
done!

2021-08-18 17:09 UTC, Gerda0283 commented on source/sass/variables.scss
> +}
done!

2021-08-18 18:46 UTC, Gerda0283 commented on source/index.html
> +          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1998.6033013998237!2d30.32136833545218!3d59.938724543317974!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4696310fca
done!

2021-08-18 18:46 UTC, Gerda0283 commented on source/catalog.html
> +          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1998.6033013998237!2d30.32136833545218!3d59.938724543317974!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4696310fca
done!

2021-08-18 18:46 UTC, Gerda0283 commented on source/form.html
> +          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1998.6033013998237!2d30.32136833545218!3d59.938724543317974!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4696310fca
done!

2021-08-19 10:32 UTC, andreysgra requested changes
Сейчас почти всё хорошо. Осталось только исправить эти небольшие ошибки.

2021-08-19 10:32 UTC, andreysgra commented on source/sass/blocks/cell.scss
> +  }
Класс не в том файле.

2021-08-19 10:32 UTC, andreysgra commented on source/sass/blocks/menu-list.scss
> +  .main-nav_closed .menu-list__item {
Класс не в том файле.

2021-08-19 10:32 UTC, andreysgra commented on source/sass/blocks/menu-list.scss
> +  .main-nav_nojs .menu-list__item {
Класс не в том файле.

2021-08-19 10:32 UTC, andreysgra commented on source/sass/blocks/menu-list.scss
> +  .main-nav_nojs .menu-list__item_current a {
Класс не в том файле.

2021-08-19 13:36 UTC, Gerda0283 commented on source/sass/blocks/cell.scss
> +  }
done!

2021-08-19 13:49 UTC, Gerda0283 commented on source/sass/blocks/menu-list.scss
> +  .main-nav_closed .menu-list__item {
done!

2021-08-19 13:49 UTC, Gerda0283 commented on source/sass/blocks/menu-list.scss
> +  .main-nav_nojs .menu-list__item_current a {
done!

2021-08-19 13:54 UTC, Gerda0283 commented on source/sass/blocks/menu-list.scss
> +  .main-nav_nojs .menu-list__item {
done!

2021-08-19 16:53 UTC, merged